/* Copia de la pelicula. Este es el sitio donde se edita el texto de las escenas.
   La pagina que se despliega (scroll.html) se GENERA desde aqui + es.html:

       node scroll-world/compose.js

   Cambiar palabras aqui es gratis. Anadir una escena NO: cada escena nueva es un
   clip de vuelo + un conector que hay que renderizar (~$8 a 1080p).

   IDIOMAS: cualquier texto acepta 'texto' o {es, en, nl, sv}. El motor pinta el
   espanol y cuelga los data-* al lado, que es lo que el traducir() de es.html busca
   cada vez que se pulsa una bandera. Falta un idioma en una cadena -> esa cadena cae
   al espanol, no se queda en blanco.

   Registro, copiado del que ya va vivo en es.html: en holandes la IA es "haar",
   en sueco es "den". Si eso cambia en es.html, cambiarlo aqui tambien.

   OJO con el CTA: nada de tel: en esta pagina. Los seis tel: de es.html apuntan al
   951 870 630, que sigue muerto y apagado por el bloque LINEA MUERTA; copiar aqui
   ese patron resucitaria un numero que no contesta. */
module.exports = {
  brand: { name: 'Prime AI', href: '#top' },
  /* Apuntaba a '#demo', que no existe: el motor no vuelca los `id` de las escenas
     en el DOM, asi que el boton llevaba muerto desde el despliegue. Al enlace real. */
  cta: { label: { es: 'Reservar una llamada', en: 'Book a call',
                  nl: 'Gesprek plannen', sv: 'Boka samtal' },
         href: 'https://cal.eu/prime.ai/intro-wa' },
  hint: { es: 'baja para entrar', en: 'scroll to step inside',
          nl: 'scroll naar binnen', sv: 'scrolla in' },
  skipLabel: { es: 'Saltar a la web', en: 'Skip to the site',
               nl: 'Naar de site', sv: 'Till webbplatsen' },
  diveScroll: 1.3,
  connScroll: 0.9,
  sections: [
    {
      id: 'obra',
      label: { es: 'La obra', en: 'The job', nl: 'De klus', sv: 'Jobbet' },
      still: 'assets/scroll/still/obra.webp',
      clip:  'assets/scroll/vid/obra.mp4',
      accent: '#C2703D',
      scroll: 1.7, linger: 0.45,
      eyebrow: { es: 'Martes, 10:40', en: 'Tuesday, 10:40',
                 nl: 'Dinsdag, 10:40', sv: 'Tisdag, 10:40' },
      title: { es: 'El teléfono suena con las manos en el sifón.',
               en: 'The phone rings with your hands under the sink.',
               nl: 'De telefoon gaat met je handen onder de gootsteen.',
               sv: 'Telefonen ringer med händerna under vasken.' },
      body: { es: 'No es que no quieras cogerlo. Es que no puedes.',
              en: "It's not that you don't want to answer. You can't.",
              nl: 'Niet dat je niet wilt opnemen. Je kunt het niet.',
              sv: 'Det är inte att du inte vill svara. Du kan inte.' },
      tags: [{ es: 'Manos ocupadas', en: 'Hands full', nl: 'Handen vol', sv: 'Händerna fulla' },
             { es: 'Suena cinco veces', en: 'Rings five times',
               nl: 'Gaat vijf keer over', sv: 'Ringer fem gånger' }],
    },
    {
      id: 'cocina',
      label: { es: 'Al otro lado', en: 'The other end', nl: 'De andere kant', sv: 'Andra änden' },
      still: 'assets/scroll/still/cocina.webp',
      clip:  'assets/scroll/vid/cocina.mp4',
      accent: '#C2703D',
      eyebrow: { es: 'Al otro lado', en: 'The other end',
                 nl: 'De andere kant', sv: 'Andra änden' },
      title: { es: 'No deja mensaje. Llama al siguiente.',
               en: 'They leave no message. They call the next one.',
               nl: 'Geen voicemail. Ze bellen de volgende.',
               sv: 'Inget meddelande. De ringer nästa.' },
      body: { es: 'El trabajo se lo lleva quien cogió el teléfono, no quien mejor lo hace.',
              en: 'The job goes to whoever answered, not to whoever does it best.',
              nl: 'De klus gaat naar wie opnam, niet naar wie het beste is.',
              sv: 'Jobbet går till den som svarade, inte till den som är bäst.' },
      tags: [{ es: 'Sin mensaje', en: 'No voicemail', nl: 'Geen voicemail', sv: 'Inget röstmeddelande' },
             { es: 'Siguiente de la lista', en: 'Next on the list',
               nl: 'De volgende op de lijst', sv: 'Nästa på listan' }],
    },
    {
      id: 'centralita',
      label: { es: 'Lo que cambia', en: 'What changes', nl: 'Wat er verandert', sv: 'Vad som ändras' },
      still: 'assets/scroll/still/centralita.webp',
      clip:  'assets/scroll/vid/centralita.mp4',
      accent: '#C2703D',
      scroll: 1.5, linger: 0.4,
      eyebrow: { es: 'Lo que cambia', en: 'What changes',
                 nl: 'Wat er verandert', sv: 'Vad som ändras' },
      title: { es: 'Contesta en dos tonos. A las tres de la mañana también.',
               en: 'It answers in two rings. At three in the morning too.',
               nl: 'Ze neemt op na twee keer overgaan. Ook om drie uur ’s nachts.',
               sv: 'Den svarar efter två signaler. Klockan tre på natten också.' },
      body: { es: 'Tu número sigue siendo tu número. No tocas nada.',
              en: 'Your number stays your number. You change nothing.',
              nl: 'Je nummer blijft je nummer. Je verandert niets.',
              sv: 'Ditt nummer förblir ditt nummer. Du ändrar ingenting.' },
      tags: [{ es: 'Dos tonos', en: 'Two rings', nl: 'Twee keer overgaan', sv: 'Två signaler' },
             { es: '24 horas', en: '24 hours', nl: '24 uur', sv: '24 timmar' },
             { es: 'Tu mismo número', en: 'Your own number',
               nl: 'Je eigen nummer', sv: 'Ditt eget nummer' }],
    },
    {
      id: 'agenda',
      label: { es: 'La cita', en: 'The booking', nl: 'De afspraak', sv: 'Bokningen' },
      still: 'assets/scroll/still/agenda.webp',
      clip:  'assets/scroll/vid/agenda.mp4',
      accent: '#C2703D',
      eyebrow: { es: 'Mientras sigues debajo del fregadero',
                 en: 'While you are still under the sink',
                 nl: 'Terwijl je nog onder de gootsteen ligt',
                 sv: 'Medan du fortfarande ligger under vasken' },
      title: { es: 'La cita ya está puesta.', en: 'The appointment is already booked.',
               nl: 'De afspraak staat al.', sv: 'Tiden är redan bokad.' },
      body: { es: 'Nombre, dirección, qué le pasa y a qué hora. Te llega escrito.',
              en: 'Name, address, what is wrong and what time. It arrives in writing.',
              nl: 'Naam, adres, wat er mis is en hoe laat. Je krijgt het op schrift.',
              sv: 'Namn, adress, vad som är fel och vilken tid. Du får det skriftligt.' },
      tags: [{ es: 'Hora confirmada', en: 'Time confirmed', nl: 'Tijd bevestigd', sv: 'Tid bekräftad' },
             { es: 'Dirección', en: 'Address', nl: 'Adres', sv: 'Adress' },
             { es: 'Motivo', en: 'Reason', nl: 'Reden', sv: 'Orsak' }],
    },
    {
      id: 'furgoneta',
      label: { es: 'A la mañana siguiente', en: 'Next morning',
               nl: 'De volgende ochtend', sv: 'Nästa morgon' },
      still: 'assets/scroll/still/furgoneta.webp',
      clip:  'assets/scroll/vid/furgoneta.mp4',
      accent: '#C2703D',
      eyebrow: { es: 'A la mañana siguiente', en: 'Next morning',
                 nl: 'De volgende ochtend', sv: 'Nästa morgon' },
      title: { es: 'A las nueve estás en su portal.', en: 'At nine you are at their door.',
               nl: 'Om negen uur sta je voor de deur.', sv: 'Klockan nio står du vid dörren.' },
      body: { es: 'El mismo trabajo que ayer se habría ido a otro.',
              en: 'The same job that yesterday would have gone to someone else.',
              nl: 'Dezelfde klus die gisteren naar een ander was gegaan.',
              sv: 'Samma jobb som igår hade gått till någon annan.' },
      tags: [{ es: 'Nueve en punto', en: 'Nine o’clock', nl: 'Negen uur', sv: 'Klockan nio' }],
    },
    {
      id: 'demo-film',
      label: { es: 'Escúchala', en: 'Hear it', nl: 'Hoor haar', sv: 'Hör den' },
      still: 'assets/scroll/still/demo.webp',
      clip:  'assets/scroll/vid/demo.mp4',
      accent: '#2563EB',
      scroll: 1.8, linger: 0.5,
      eyebrow: { es: 'Compruébalo', en: 'See for yourself', nl: 'Zie het zelf', sv: 'Se själv' },
      title: { es: 'Escúchala contestar.', en: 'Hear it answer.',
               nl: 'Hoor haar opnemen.', sv: 'Hör den svara.' },
      body: { es: 'Sigue bajando: debajo está todo — la calculadora, la demo en directo y el precio.',
              en: 'Keep scrolling: it is all below — the calculator, the live demo and the price.',
              nl: 'Scroll verder: alles staat hieronder — de rekenhulp, de live demo en de prijs.',
              sv: 'Fortsätt scrolla: allt finns nedanför — kalkylatorn, livedemon och priset.' },
      tags: [],
      cta: { primary: { label: { es: 'Reservar una llamada conmigo', en: 'Book a call with me',
                                 nl: 'Gesprek met mij plannen', sv: 'Boka ett samtal med mig' },
                        href: 'https://cal.eu/prime.ai/intro-wa' } },
    },
  ],
  connectors: [
    'assets/scroll/vid/conn_0.mp4',
    'assets/scroll/vid/conn_1.mp4',
    'assets/scroll/vid/conn_2.mp4',
    'assets/scroll/vid/conn_3.mp4',
    'assets/scroll/vid/conn_4.mp4',
  ],
};
